version: '3.3'

services:
   web-service:
     depends_on:
       - model-service
     image: alepeco/pecorale-djl-serving:latest
     ports:
       - "80:8082"
     restart: always

   model-service:
     image: alepeco/djl-serving:latest
     restart: always

